// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:jhumo/moduls/methods.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    kIsWeb.toPrint;
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFgC4yLJB-U_427fqMOcHKcKeffbHVB6Y',
    appId: '1:997359602496:web:cb590ae42060aab46088a5',
    messagingSenderId: '997359602496',
    projectId: 'takecare-290c9',
    authDomain: 'takecare-290c9.firebaseapp.com',
    databaseURL: 'https://takecare-290c9-default-rtdb.firebaseio.com',
    storageBucket: 'takecare-290c9.appspot.com',
    measurementId: 'G-ZZZR7SV522',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuK8JH8RdUky31SX5RFmUjQwT_3omyhEs',
    appId: '1:997359602496:android:e558f190ffb057e36088a5',
    messagingSenderId: '997359602496',
    projectId: 'takecare-290c9',
    storageBucket: 'takecare-290c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2hEAB8YdcRTyUiuex4rhinkAkqQyYyvk',
    appId: '1:997359602496:ios:8c06804966e736b46088a5',
    messagingSenderId: '997359602496',
    projectId: 'takecare-290c9',
    storageBucket: 'takecare-290c9.appspot.com',
    iosBundleId: 'com.example.jhumo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2hEAB8YdcRTyUiuex4rhinkAkqQyYyvk',
    appId: '1:997359602496:ios:8c06804966e736b46088a5',
    messagingSenderId: '997359602496',
    projectId: 'takecare-290c9',
    storageBucket: 'takecare-290c9.appspot.com',
    iosBundleId: 'com.example.jhumo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFgC4yLJB-U_427fqMOcHKcKeffbHVB6Y',
    appId: '1:997359602496:web:c59583d89cf194586088a5',
    messagingSenderId: '997359602496',
    projectId: 'takecare-290c9',
    authDomain: 'takecare-290c9.firebaseapp.com',
    storageBucket: 'takecare-290c9.appspot.com',
    measurementId: 'G-QK7Q27FQGE',
  );

}